### ISSUE TITLE
Let's Team Up

### ISSUE THREAD

**Issue by cabusao10** [CarlosX/TestProjects#3]
Hey there, sorry for late reply, are you still interested to team up with this project? I would like to make this project private, you can email at cabusaorhen14@gmail.com or if you have Facebook account you can visit my page and PM there. www.facebook.com/GodsWarPrivateServer

**Comment by Try-Parser** [comment]
I would like to team up with you guys. do you guys have some road map or some like task you want us to work for or design ?
